name: flutter_whip
version: 0.5.4
description: WebRTC-HTTP ingestion protocol (WHIP) library for flutter.
homepage: https://github.com/cloudwebrtc/flutter-whip.git
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter_webrtc: ^0.12.5+hotfix.2
  http: ^1.2.2
  sdp_transform: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  test: any
